# Generated by Django 4.2.1 on 2023-06-01 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_useractivity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
